language: python
python:
  - "2.7"

env:
  - DJANGO="django==1.7"
  - DJANGO="django==1.8"
  - DJANGO="django==1.9"
  - DJANGO="django==1.10"

install:
  - pip install -q $DJANGO --use-mirrors


branches:
  only:
    - master

script:
  - python dajaxice/tests/runtests.py
